FROM almalinux:9
ENV name="hari" \
    course="devops" \
    version="1.0"
CMD [ "sleep","100" ]
# you  can access the env variables in the container
# env variables location --> :: docker exec -it <container id> bash :: :: env ::
# available env variables that location --> :: docker exec -it <container id> env ::