FROM almalinux:9
LABEL author="hari" \
      course="devops" \
      version="1.0"
# how to use labels
# docker build -t label:1.0 .
# docker images -f label=course=devops
# docker images -f label=version=1.0
# docker images -f label=author=hari
# docker images -f label=course=devops -f label=version=1.0
# docker images -f label=course=devops -f label=author=hari